-- Drop existing tables if they exist to start fresh
DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS stations CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- Create Settings table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Create Stations table
CREATE TABLE stations (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  passkey TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL
);

-- Create Slots table
CREATE TABLE slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id BIGINT NOT NULL,
  slot_index BIGINT NOT NULL,
  status TEXT NOT NULL,
  type TEXT NOT NULL,
  power TEXT NOT NULL,
  CONSTRAINT fk_station FOREIGN KEY (station_id) REFERENCES stations(id) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE slots ENABLE ROW LEVEL SECURITY;

-- Allow all actions for both service_role (backend) and anon (public key) for testing/development ease
CREATE POLICY "Allow all to service_role" ON settings TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to service_role" ON stations TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to service_role" ON slots TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow all to anon" ON settings TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to anon" ON stations TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to anon" ON slots TO anon USING (true) WITH CHECK (true);

-- Seed Settings
INSERT INTO settings (key, value) VALUES ('adminPasskey', 'ADMIN123');

-- Seed Stations (7 Real-World EV hubs in Bengaluru)
INSERT INTO stations (id, name, passkey, lat, lng) VALUES
(1, 'Taj West End Charging Hub', 'TAJ123', 12.9786, 77.5843),
(2, 'BESCOM KR Circle Station', 'BESCOM456', 12.9748, 77.5855),
(3, 'UB City Charging Point', 'UBCITY789', 12.9722, 77.5958),
(4, 'Croma Koramangala Station', 'CROMA000', 12.9344, 77.6200),
(5, 'Phoenix Marketcity Station', 'PHOENIX555', 12.9958, 77.6963),
(6, 'Electronic City EZ Charge', 'ECITY888', 12.8468, 77.6766),
(7, 'Jayanagar 4th Block Node', 'JAYANAGAR222', 12.9290, 77.5828);

-- Seed Slots (5 slots per station with realistic values)
INSERT INTO slots (station_id, slot_index, status, type, power) VALUES
-- Taj West End (1)
(1, 101, 'empty', 'DC Fast', '150kW'),
(1, 102, 'empty', 'DC Fast', '150kW'),
(1, 103, 'full', 'AC Type-2', '22kW'),
(1, 104, 'empty', 'AC Type-2', '22kW'),
(1, 105, 'empty', 'AC Type-2', '7.4kW'),

-- BESCOM KR Circle (2)
(2, 201, 'empty', 'DC Fast', '50kW'),
(2, 202, 'empty', 'DC Fast', '50kW'),
(2, 203, 'empty', 'AC Type-2', '22kW'),
(2, 204, 'full', 'AC Type-2', '22kW'),
(2, 205, 'empty', 'AC Type-2', '7.4kW'),

-- UB City (3)
(3, 301, 'empty', 'DC Fast', '100kW'),
(3, 302, 'empty', 'DC Fast', '100kW'),
(3, 303, 'empty', 'DC Fast', '100kW'),
(3, 304, 'full', 'AC Type-2', '22kW'),
(3, 305, 'empty', 'AC Type-2', '22kW'),

-- Croma Koramangala (4)
(4, 401, 'empty', 'DC Fast', '60kW'),
(4, 402, 'empty', 'DC Fast', '60kW'),
(4, 403, 'empty', 'AC Type-2', '22kW'),
(4, 404, 'empty', 'AC Type-2', '7.4kW'),
(4, 405, 'empty', 'AC Type-2', '7.4kW'),

-- Phoenix Marketcity (5)
(5, 501, 'empty', 'DC Fast', '120kW'),
(5, 502, 'empty', 'DC Fast', '120kW'),
(5, 503, 'empty', 'AC Type-2', '22kW'),
(5, 504, 'empty', 'AC Type-2', '22kW'),
(5, 505, 'full', 'AC Type-2', '7.4kW'),

-- Electronic City (6)
(6, 601, 'empty', 'DC Fast', '150kW'),
(6, 602, 'empty', 'DC Fast', '150kW'),
(6, 603, 'empty', 'DC Fast', '150kW'),
(6, 604, 'empty', 'AC Type-2', '22kW'),
(6, 605, 'empty', 'AC Type-2', '22kW'),

-- Jayanagar (7)
(7, 701, 'empty', 'DC Fast', '50kW'),
(7, 702, 'empty', 'AC Type-2', '22kW'),
(7, 703, 'empty', 'AC Type-2', '22kW'),
(7, 704, 'empty', 'AC Type-2', '7.4kW'),
(7, 705, 'empty', 'AC Type-2', '7.4kW');
